import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, FileText, TrendingUp, AlertCircle, Users, CheckCircle2, Zap, ShieldCheck, Globe, Target } from 'lucide-react';
import { useAppStore } from '../../store/useAppStore';
import { Button, Card, Badge } from '../common';
import { useTeamHealth } from '../../hooks/useTeamHealth';
import { cn } from '../../utils/cn';

/**
 * TeamHealthReportModal: The Executive Intelligence Summary
 * High-performance boardroom report for project stakeholders.
 */
export const TeamHealthReportModal = () => {
  const { showHealthReport, setShowHealthReport, tasks, team, blockers } = useAppStore();
  const { score, risk, burnout, collaboration, overdueCount } = useTeamHealth();

  const handleDownload = () => {
    const content = `
SYNC SPHERE AI — EXECUTIVE INTELLIGENCE REPORT
Generated: ${new Date().toLocaleString()}
Classification: CONFIDENTIAL / STRATEGIC

1. EXECUTIVE SUMMARY
-------------------
Synchronized Health Score: ${score}/100
Operational Risk Level: ${risk < 30 ? 'OPTIMAL' : risk < 60 ? 'ELEVATED' : 'CRITICAL'}
Team Collaboration Index: ${collaboration}%
Resource Burnout Signal: ${burnout}%

2. OPERATIONAL METRICS
---------------------
Total Deliverables: ${tasks.length}
Overdue Items: ${overdueCount}
Active Blockers: ${blockers.length}
Sprint Velocity: 48 pts (12% above baseline)

3. STRATEGIC RECOMMENDATIONS
---------------------------
- Workload Balancing: ${team.some(m => m.workloadPercent > 85) ? 'Redistribute tasks from overloaded members.' : 'Current load distribution is optimal.'}
- Blocker Orchestration: ${blockers.length > 0 ? `Prioritize resolution of ${blockers.length} critical inhibitors.` : 'No critical blockers detected.'}
- Velocity Optimization: Maintain current synchronization rhythm to meet EOW targets.

Generated by SyncSphere AI Orchestration Engine.
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `SyncSphere-Executive-Report-${Date.now()}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  const scoreColor = score > 80 ? 'text-emerald-400' : score > 50 ? 'text-amber-400' : 'text-rose-400';
  const scoreGradient = score > 80 ? 'from-emerald-500/20 to-teal-500/0' : score > 50 ? 'from-amber-500/20 to-orange-500/0' : 'from-rose-500/20 to-red-600/0';

  return (
    <AnimatePresence>
      {showHealthReport && (
        <>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/80 backdrop-blur-xl z-[100]"
            onClick={() => setShowHealthReport(false)} />
          
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 40 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 40 }}
            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            className="fixed inset-0 z-[101] flex items-center justify-center p-6 pointer-events-none"
          >
            <Card className="w-full max-w-4xl max-h-[90vh] overflow-hidden p-0 border-white/10 shadow-[0_0_100px_rgba(0,0,0,0.5)] pointer-events-auto bg-black/90">
              <div className="flex flex-col md:flex-row h-full">
                {/* Left Sidebar: Executive Summary */}
                <div className={cn("w-full md:w-80 p-8 bg-gradient-to-b border-b md:border-b-0 md:border-r border-white/5", scoreGradient)}>
                  <div className="flex items-center gap-3 mb-10">
                    <div className="p-3 rounded-2xl accent-gradient shadow-lg glow-primary">
                      <Target className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h2 className="text-xl font-black text-white leading-none">SyncSphere</h2>
                      <p className="text-[10px] text-white/30 font-black uppercase tracking-widest mt-1">Report v2.4</p>
                    </div>
                  </div>

                  <div className="text-center mb-10">
                    <div className="relative inline-block">
                      <svg className="w-40 h-40 -rotate-90" viewBox="0 0 100 100">
                        <circle cx="50" cy="50" r="45" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="4" />
                        <motion.circle 
                          cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="4"
                          initial={{ strokeDasharray: "0 283" }}
                          animate={{ strokeDasharray: `${(score / 100) * 283} 283` }}
                          transition={{ duration: 1.5, ease: "easeOut" }}
                          className={scoreColor}
                          strokeLinecap="round" 
                        />
                      </svg>
                      <div className="absolute inset-0 flex flex-col items-center justify-center">
                        <span className={cn("text-5xl font-black tracking-tighter", scoreColor)}>{score}%</span>
                        <span className="text-[9px] font-black text-white/30 uppercase tracking-[0.2em]">Health Index</span>
                      </div>
                    </div>
                  </div>

                  <div className="space-y-4">
                    <div className="p-4 rounded-2xl bg-white/5 border border-white/5">
                      <p className="text-[10px] font-black text-white/20 uppercase tracking-widest mb-2">Primary Risk Signal</p>
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-bold text-white/80">{risk < 40 ? 'Minimal' : risk < 70 ? 'Moderate' : 'Critical'}</span>
                        <Badge label={`${risk}%`} variant={risk > 60 ? 'high' : 'neutral'} />
                      </div>
                    </div>
                    <div className="p-4 rounded-2xl bg-white/5 border border-white/5">
                      <p className="text-[10px] font-black text-white/20 uppercase tracking-widest mb-2">Team Sentiment</p>
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-bold text-white/80">Synchronized</span>
                        <Badge label="Optimal" variant="success" />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Right Panel: Detailed Intelligence */}
                <div className="flex-1 flex flex-col overflow-hidden">
                  <div className="p-8 border-b border-white/5 flex items-center justify-between bg-white/[0.02]">
                    <div>
                      <h3 className="text-2xl font-black text-white tracking-tight">Executive Intelligence Report</h3>
                      <p className="text-sm text-white/40 mt-1 flex items-center gap-2">
                        <Globe className="w-3 h-3" /> Global synchronization data for {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}
                      </p>
                    </div>
                    <button onClick={() => setShowHealthReport(false)} className="p-2 rounded-xl hover:bg-white/10 text-white/20 hover:text-white transition-all">
                      <X className="w-6 h-6" />
                    </button>
                  </div>

                  <div className="flex-1 overflow-y-auto p-8 space-y-8 custom-scrollbar">
                    {/* KPI Matrix */}
                    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                      {[
                        { label: 'Deliverables', value: tasks.length, icon: FileText, color: 'text-indigo-400' },
                        { label: 'Completed', value: tasks.filter(t=>t.status==='completed').length, icon: CheckCircle2, color: 'text-emerald-400' },
                        { label: 'Blockers', value: blockers.length, icon: AlertCircle, color: 'text-rose-400' },
                        { label: 'Overdue', value: overdueCount, icon: TrendingUp, color: 'text-amber-400' },
                      ].map(stat => (
                        <div key={stat.label} className="p-4 rounded-2xl bg-white/5 border border-white/5">
                          <stat.icon className={cn("w-4 h-4 mb-2", stat.color)} />
                          <p className="text-xl font-black text-white">{stat.value}</p>
                          <p className="text-[9px] font-black text-white/20 uppercase tracking-widest">{stat.label}</p>
                        </div>
                      ))}
                    </div>

                    {/* AI Strategic Advice */}
                    <div className="space-y-4">
                      <div className="flex items-center gap-2 mb-4">
                        <Zap className="w-4 h-4 text-accent-primary" />
                        <h4 className="text-sm font-black text-white uppercase tracking-widest">AI Strategic Recommendations</h4>
                      </div>
                      <div className="grid grid-cols-1 gap-3">
                        {[
                          { title: 'Resource Realignment', text: `Workload imbalance detected at ${burnout}%. Consider redistributing high-density tasks across the team to maintain velocity.`, icon: Users, color: 'rose' },
                          { title: 'Blocker Escalation', text: `Critical inhibitor "${blockers[0]?.title || 'Auth Integration'}" is affecting ${risk}% of deliverables. Escalation recommended.`, icon: ShieldCheck, color: 'amber' },
                          { title: 'Velocity Stability', text: 'Team output is 12% above the 30-day baseline. Current orchestration strategy is highly effective.', icon: TrendingUp, color: 'emerald' },
                        ].map((advice, i) => (
                          <div key={i} className="flex gap-4 p-5 rounded-3xl bg-white/5 border border-white/5 hover:border-white/10 transition-all group">
                            <div className={cn("p-3 rounded-2xl shrink-0 h-fit transition-colors", 
                              advice.color === 'rose' ? 'bg-rose-500/10 text-rose-400' : 
                              advice.color === 'amber' ? 'bg-amber-500/10 text-amber-400' : 'bg-emerald-500/10 text-emerald-400'
                            )}>
                              <advice.icon className="w-5 h-5" />
                            </div>
                            <div>
                              <h5 className="font-bold text-white text-sm mb-1">{advice.title}</h5>
                              <p className="text-sm text-white/50 leading-relaxed font-medium">{advice.text}</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Report Actions */}
                  <div className="p-8 border-t border-white/5 bg-white/[0.02] flex items-center gap-4">
                    <Button variant="primary" onClick={handleDownload} className="flex-1 py-4" icon={Download}>
                      Download Boardroom Report
                    </Button>
                    <Button variant="secondary" onClick={() => setShowHealthReport(false)} className="py-4">
                      Close Intelligence
                    </Button>
                  </div>
                </div>
              </div>
            </Card>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};
