import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, FileText, TrendingUp, AlertCircle, Users, CheckCircle2, Zap } from 'lucide-react';
import { useAppStore } from '../../store/useAppStore';

export const TeamHealthReportModal = () => {
  const { showHealthReport, setShowHealthReport, tasks, team, blockers, riskScore } = useAppStore();
  const completed = tasks.filter(t => t.status === 'completed').length;
  const inProgress = tasks.filter(t => t.status === 'in-progress').length;
  const blocked = tasks.filter(t => t.isBlocked).length;
  const healthScore = Math.max(10, 100 - riskScore * 3 - blocked * 10);

  const handleDownload = () => {
    const content = `
SyncSphere AI — Team Health Report
Generated: ${new Date().toLocaleString()}
=======================================

OVERVIEW
Health Score: ${healthScore}/100
Risk Level: ${riskScore < 30 ? 'Low' : riskScore < 60 ? 'Medium' : 'High'}
Active Blockers: ${blockers.length}
Sprint Velocity: 48 pts

TASK BREAKDOWN
Total Tasks: ${tasks.length}
Completed: ${completed}
In Progress: ${inProgress}
Blocked: ${blocked}
Completion Rate: ${Math.round((completed / tasks.length) * 100)}%

TEAM WORKLOAD
${team.map(m => `${m.name} (${m.role}): ${m.workloadPercent}% load — ${m.tasksCount} tasks`).join('\n')}

ACTIVE BLOCKERS
${blockers.map(b => `[${b.severity.toUpperCase()}] ${b.title} — ${b.assignee}`).join('\n')}

AI RECOMMENDATIONS
1. Alex Rivera is at ${team.find(m => m.name === 'Alex Rivera')?.workloadPercent}% capacity — consider redistributing tasks.
2. Auth flow blocker is on the critical path — escalate immediately.
3. Team velocity is above baseline by 12% — maintain current sprint rhythm.

Generated by SyncSphere AI • Mission Intelligence Platform
    `.trim();
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `syncsphere-health-report-${Date.now()}.txt`; a.click();
    URL.revokeObjectURL(url);
  };

  const scoreColor = healthScore > 70 ? 'text-emerald-400' : healthScore > 40 ? 'text-amber-400' : 'text-rose-400';
  const scoreGradient = healthScore > 70 ? 'from-emerald-500 to-teal-500' : healthScore > 40 ? 'from-amber-500 to-orange-500' : 'from-rose-500 to-red-600';

  return (
    <AnimatePresence>
      {showHealthReport && (
        <>
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/70 backdrop-blur-md z-[100]"
            onClick={() => setShowHealthReport(false)} />
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 40 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.9, y: 40 }}
            transition={{ type: 'spring', damping: 28, stiffness: 280 }}
            className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-2xl z-[101] px-4"
          >
            <div className="glass rounded-[2rem] overflow-hidden border border-white/10 shadow-2xl">
              {/* Header */}
              <div className="relative p-8 pb-6 border-b border-white/5">
                <div className={`absolute inset-0 bg-gradient-to-br ${scoreGradient} opacity-5`} />
                <div className="relative flex items-start justify-between">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <FileText className="w-5 h-5 text-accent-primary" />
                      <span className="text-[10px] font-black uppercase tracking-widest text-accent-primary">AI Generated Report</span>
                    </div>
                    <h2 className="text-2xl font-black text-white">Team Health Report</h2>
                    <p className="text-sm text-white/50 mt-1">{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}</p>
                  </div>
                  <button onClick={() => setShowHealthReport(false)} className="p-2 rounded-xl hover:bg-white/10 text-white/40 hover:text-white transition-all">
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {/* Big Score */}
                <div className="mt-6 flex items-center gap-6">
                  <div className="relative w-24 h-24">
                    <svg className="w-24 h-24 -rotate-90" viewBox="0 0 100 100">
                      <circle cx="50" cy="50" r="42" fill="none" stroke="rgba(255,255,255,0.05)" strokeWidth="8" />
                      <circle cx="50" cy="50" r="42" fill="none" stroke="url(#scoreGrad)" strokeWidth="8"
                        strokeDasharray={`${healthScore * 2.64} 264`} strokeLinecap="round" />
                      <defs>
                        <linearGradient id="scoreGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                          <stop offset="0%" stopColor="#6366f1" />
                          <stop offset="100%" stopColor="#a855f7" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <div className="absolute inset-0 flex items-center justify-center flex-col">
                      <span className={`text-2xl font-black ${scoreColor}`}>{healthScore}</span>
                      <span className="text-[8px] text-white/30 font-bold uppercase">SCORE</span>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-3 flex-1">
                    {[
                      { label: 'Velocity', value: '48 pts', icon: TrendingUp, color: 'text-emerald-400' },
                      { label: 'Blockers', value: `${blockers.length} active`, icon: AlertCircle, color: 'text-rose-400' },
                      { label: 'Capacity', value: '94.2%', icon: Users, color: 'text-indigo-400' },
                      { label: 'Done', value: `${completed}/${tasks.length}`, icon: CheckCircle2, color: 'text-teal-400' },
                    ].map(stat => (
                      <div key={stat.label} className="p-3 rounded-2xl bg-white/5 border border-white/5 flex items-center gap-2">
                        <stat.icon className={`w-4 h-4 ${stat.color}`} />
                        <div>
                          <p className="text-white font-bold text-sm">{stat.value}</p>
                          <p className="text-[10px] text-white/40 uppercase tracking-wide">{stat.label}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* AI Insights */}
              <div className="p-8 pt-6 space-y-4">
                <h3 className="text-sm font-black text-white/50 uppercase tracking-widest">AI Recommendations</h3>
                {[
                  { level: 'warning', text: `Alex Rivera is at ${team.find(m=>m.name==='Alex Rivera')?.workloadPercent}% capacity — consider redistributing 1-2 tasks.` },
                  { level: 'danger', text: 'Auth flow blocker is on the critical path — escalate to security team immediately.' },
                  { level: 'success', text: 'Team velocity is up 12% from last sprint. Elena\'s design work is unblocking frontend.' },
                ].map((r, i) => (
                  <div key={i} className={`p-4 rounded-2xl border flex items-start gap-3 ${
                    r.level === 'warning' ? 'bg-amber-500/5 border-amber-500/20' :
                    r.level === 'danger' ? 'bg-rose-500/5 border-rose-500/20' :
                    'bg-emerald-500/5 border-emerald-500/20'
                  }`}>
                    <Zap className={`w-4 h-4 shrink-0 mt-0.5 ${
                      r.level === 'warning' ? 'text-amber-400' : r.level === 'danger' ? 'text-rose-400' : 'text-emerald-400'
                    }`} />
                    <p className="text-sm text-white/80">{r.text}</p>
                  </div>
                ))}
              </div>

              {/* Footer */}
              <div className="px-8 pb-8">
                <button onClick={handleDownload}
                  className="w-full flex items-center justify-center gap-3 py-4 rounded-2xl accent-gradient font-black text-white text-sm glow-primary hover:opacity-90 transition-opacity active:scale-95">
                  <Download className="w-4 h-4" />
                  DOWNLOAD FULL REPORT
                </button>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
};
